spring:
  datasource:
    test-on-borrow: true
    validation-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pws?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  devtools:
    restart:
      exclude: static/**, templates/**
debug: true

#server:
#  tomcat:
#    basedir: e://logs
#    accesslog:
#      directory: logs
#      enabled: true
#      pattern: common
#  port: 8080
#
#chrome:
#  driver:
#    location: e://chromedriver
#    poolSize: 1
#
#logging:
#  file: e://logs//xxxx.log